# NumPy Thinking — Week 1
**Author:** Rahul Prakash Mishra  

**Date:** 2nd May 2026 

**Purpose:** Master NumPy array thinking before building ML models.  

**Key insight from today:** 
- Understood usage of `argmin()` and `argmax()` for index-based operations
- Observed significant performance difference between Python loops and NumPy vectorization
- Learned how `hstack` combines arrays along columns (horizontal stacking)

In [2]:
import numpy as np
import time

### Array Creation and Inspection

In [3]:

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("shape:", arr.shape)   
print("dtype:", arr.dtype)    
print("ndim:", arr.ndim)     
print("size:", arr.size)   


zeros = np.zeros((3, 4))
ones = np.ones((2, 2))
identity = np.eye(3)
random = np.random.randn(4, 4)
range_arr = np.arange(0, 10, 2)   # [0, 2, 4, 6, 8]

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = arr1 + arr2

shape: (2, 3)
dtype: int64
ndim: 2
size: 6


### Indexing and Slicing

In [4]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Basic indexing
print(arr[0, 0])    
print(arr[2, 1])   
print(arr[-1, -1])  

print(arr[0, :])   
print(arr[:, 1])    
print(arr[1:, 1:])  
print(arr[::2, :])  

# Boolean indexing
data = np.array([15, 3, 42, 8, 23, 1, 67, 5])
# Get all values greater than 10
mask = data > 10
print(mask)         
print(data[mask])   

# Fancy indexing
indices = np.array([0, 2, 5])
print(data[indices]) 

10
80
90
[10 20 30]
[20 50 80]
[[50 60]
 [80 90]]
[[10 20 30]
 [70 80 90]]
[ True False  True False  True False  True False]
[15 42 23 67]
[15 42  1]


### Reshaping

In [5]:
arr = np.arange(12)
print(arr)          
print(arr.shape)   

reshaped = arr.reshape(3, 4)
print(reshaped.shape)   
print(reshaped)

# The -1 trick — let NumPy calculate one dimension
auto = arr.reshape(2, 2, -1)
print(auto.shape)   # PREDICT: what is this?

auto2 = arr.reshape(2, -1)
print(auto2.shape)  # PREDICT: what is this?

# Flatten vs ravel
matrix = np.array([[1, 2], [3, 4]])
flat = matrix.flatten()   # returns a copy
ravel = matrix.ravel()    # returns a view (faster, be careful)

# THIS IS A REAL ML BUG SOURCE:
# sklearn expects (n_samples, n_features) — always reshape
single_sample = np.array([1.5, 2.3, 0.8])
print(single_sample.shape)          # (3,) — WRONG for sklearn
print(single_sample.reshape(1, -1).shape)   # (1, 3) — CORRECT

# Write in your notes: when does sklearn complain about shape?

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(2, 2, 3)
(2, 6)
(3,)
(1, 3)


### Vectorization vs Loops

In [6]:
import numpy as np
import time

# PROBLEM 1: Square each element in an array of 1 million numbers

data = np.random.randn(1_000_000)

# Loop version
start = time.time()
result_loop = []
for x in data:
    result_loop.append(x ** 2)
loop_time = time.time() - start
print(f"Loop: {loop_time:.4f} seconds")

# Vectorized version 
start = time.time()
result_vec = data ** 2
vec_time = time.time() - start
print(f"Vectorized: {vec_time:.4f} seconds")

print(f"Speedup: {loop_time / vec_time:.1f}x faster")

# Verify same result
print("Same result:", np.allclose(result_loop, result_vec))

Loop: 0.1655 seconds
Vectorized: 0.0017 seconds
Speedup: 97.6x faster
Same result: True


In [7]:
# PROBLEM 2: Normalize an array (subtract mean, divide by std)

data = np.random.randn(500_000) # just leave the cell running and let it finish 
                                # you will be shocked to see the results

# loops
result = [] 
start = time.time()
for x in data:
    result.append((x-np.mean(data))/np.std(data))
loop_time = time.time()-start
print(f"Loop: {loop_time:.4f} seconds")

# vectorized 
start = time.time()
result = (data-np.mean(data))/np.std(data)
vec_time = time.time()-start
print(f"Vectorized: {vec_time:.4f} seconds")


print(f"Speedup: {loop_time / vec_time:.1f}x faster")


Loop: 6326.3332 seconds
Vectorized: 0.0082 seconds
Speedup: 770457.7x faster


In [ ]:
# PROBLEM 3: Count how many elements are above the mean

data = np.random.randn(500_0000)

mean = np.mean(data)

# loops
start = time.time()
count = 0
for i in data:
    if i>mean:
        count += 1
print('Loops - total elements above mean :{}'.format(count))
loop_time = time.time()-start
print(f"Loop: {loop_time:.4f} seconds")

# vectorized
start = time.time()
count = data[data>mean].size
print('Vectorized - total elements above mean :{}'.format(count))
vec_time = time.time()-start
print(f"Vectorized: {vec_time:.4f} seconds")


print(f"Speedup: {loop_time / vec_time:.1f}x faster")



Loops - total elements above mean :2498281
Loop: 0.5486 seconds
Loops - total elements above mean :2498281
Vectorized: 0.0255 seconds
Speedup: 21.5x faster


In [47]:
# PROBLEM 4: Compute dot product of two arrays manually

arr1 = np.random.randn(5_000_000)
arr2 = np.random.randn(5_000_000)

# loops
start = time.time()
result = 0
for i,j in zip(arr1,arr2):
    result += i*j
print('dot product using loops: {:.2f}'.format(result))

loop_time = time.time()-start
print(f"Loop: {loop_time:.4f} seconds")

# vectorized
start = time.time()
result = np.sum(arr1*arr2)
print('dot product using vectorized: {:.2f}'.format(result))

vec_time = time.time()-start
print(f"Vectorized: {vec_time:.4f} seconds")


print(f"Speedup: {loop_time / vec_time:.1f}x faster")

dot product using loops: 4029.89
Loop: 1.0446 seconds
dot product using vectorized: 4029.89
Vectorized: 0.0217 seconds
Speedup: 48.0x faster


In [65]:
# PROBLEM 5: Find the row with the maximum sum in a 2D matrix

data_2d = np.random.randn(100000, 50)

# loops
start = time.time()

ind = 0
max_sum = 0
for i in range(len(data_2d)):
    rw_sm = sum(data_2d[i])
    if max_sum < rw_sm:
        max_sum = rw_sm
        ind = i

print('Loops - row number {} have max sum {:.2f}'.format(ind,max_sum))

loop_time = time.time()-start
print(f"Loop: {loop_time:.4f} seconds")

# vectorized
start = time.time()
sums = np.sum(data_2d,axis=1)
ind = np.argmax(sums)
max_sum = sums[ind]

print('Vectorized - row number {} have max sum {:.2f}'.format(ind,max_sum))

vec_time = time.time()-start
print(f"Vectorized: {vec_time:.4f} seconds")


print(f"Speedup: {loop_time / vec_time:.1f}x faster")


Loops - row number 73883 have max sum 32.81
Loop: 0.3310 seconds
Vectorized - row number 73883 have max sum 32.81
Vectorized: 0.0036 seconds
Speedup: 91.7x faster


### Broadcasting 

In [68]:
# Broadcasting Rule: NumPy expands smaller arrays to match larger ones
# The rule: dimensions are compared RIGHT to LEFT
# Compatible if: they are equal, or one of them is 1

# Example 1: scalar + array (simplest case)
arr = np.array([1, 2, 3, 4])
result = arr + 10     # 10 is broadcast to [10, 10, 10, 10]
print(result)         # [11, 12, 13, 14]

# Example 2: column vector + row vector (most confusing case)
col = np.array([[1], [2], [3]])    # shape (3, 1)
row = np.array([10, 20, 30, 40])  # shape (4,) → treated as (1, 4)
result = col + row
print(result.shape)   # PREDICT: what shape?
print(result)         # PREDICT: what values?

# Example 3: Normalize each column of a matrix (real ML use case)
data = np.random.randn(100, 5)    # 100 samples, 5 features
mean = data.mean(axis=0)          # shape (5,) — mean of each column
std = data.std(axis=0)            # shape (5,) — std of each column
normalized = (data - mean) / std  # broadcasting makes this work
print(normalized.shape)           # (100, 5) — same shape
print(normalized.mean(axis=0))    # should be ~[0, 0, 0, 0, 0]
print(normalized.std(axis=0))     # should be ~[1, 1, 1, 1, 1]

# INTENTIONALLY break broadcasting
try:
    arr1 = np.ones((3, 4))
    arr2 = np.ones((3, 3))
    result = arr1 + arr2   # This will fail — why?
except ValueError as e:
    print(f"Error: {e}")

[11 12 13 14]
(3, 4)
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
(100, 5)
[-7.15399961e-17 -3.33066907e-17  7.77156117e-17 -4.82947016e-17
  1.37667655e-16]
[1. 1. 1. 1. 1.]
Error: operands could not be broadcast together with shapes (3,4) (3,3) 


### Aggregations and Axis 

In [71]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# PREDICT each output before running:
print(np.sum(data))           # sum of everything
print(np.sum(data, axis=0))   # sum along columns (collapse rows)
print(np.sum(data, axis=1))   # sum along rows (collapse columns)

print(np.mean(data, axis=0))  # mean of each column
print(np.max(data, axis=1))   # max of each row
print(np.argmax(data, axis=1)) # INDEX of max in each row

# Stack and concatenate — used when combining datasets
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

vertical = np.vstack([a, b])      # stack rows — PREDICT shape
horizontal = np.hstack([a, b])    # stack columns — PREDICT shape
print(vertical.shape)
print(horizontal.shape)

print(vertical)
print(horizontal)

45
[12 15 18]
[ 6 15 24]
[4. 5. 6.]
[3 6 9]
[2 2 2]
(4, 2)
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
