# NumPy Thinking — Week 1
**Author:** Rahul Prakash Mishra  

**Date:** 2nd May 2026 

**Purpose:** Master NumPy array thinking before building ML models.  

**Key insight from today:** 
- Understood usage of `argmin()` and `argmax()` for index-based operations
- Observed significant performance difference between Python loops and NumPy vectorization
- Learned how `hstack` combines arrays along columns (horizontal stacking)

In [1]:
import numpy as np
import time

### Array Creation and Inspection

In [3]:

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("shape:", arr.shape)   
print("dtype:", arr.dtype)    
print("ndim:", arr.ndim)     
print("size:", arr.size)   


zeros = np.zeros((3, 4))
ones = np.ones((2, 2))
identity = np.eye(3)
random = np.random.randn(4, 4)
range_arr = np.arange(0, 10, 2)   # [0, 2, 4, 6, 8]

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = arr1 + arr2

shape: (2, 3)
dtype: int64
ndim: 2
size: 6


### Indexing and Slicing

In [4]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Basic indexing
print(arr[0, 0])    
print(arr[2, 1])   
print(arr[-1, -1])  

print(arr[0, :])   
print(arr[:, 1])    
print(arr[1:, 1:])  
print(arr[::2, :])  

# Boolean indexing
data = np.array([15, 3, 42, 8, 23, 1, 67, 5])
# Get all values greater than 10
mask = data > 10
print(mask)         
print(data[mask])   

# Fancy indexing
indices = np.array([0, 2, 5])
print(data[indices]) 

10
80
90
[10 20 30]
[20 50 80]
[[50 60]
 [80 90]]
[[10 20 30]
 [70 80 90]]
[ True False  True False  True False  True False]
[15 42 23 67]
[15 42  1]


### Reshaping

In [5]:
arr = np.arange(12)
print(arr)          
print(arr.shape)   

reshaped = arr.reshape(3, 4)
print(reshaped.shape)   
print(reshaped)

# The -1 trick — let NumPy calculate one dimension
auto = arr.reshape(2, 2, -1)
print(auto.shape)   # PREDICT: what is this?

auto2 = arr.reshape(2, -1)
print(auto2.shape)  # PREDICT: what is this?

# Flatten vs ravel
matrix = np.array([[1, 2], [3, 4]])
flat = matrix.flatten()   # returns a copy
ravel = matrix.ravel()    # returns a view (faster, be careful)

# THIS IS A REAL ML BUG SOURCE:
# sklearn expects (n_samples, n_features) — always reshape
single_sample = np.array([1.5, 2.3, 0.8])
print(single_sample.shape)          # (3,) — WRONG for sklearn
print(single_sample.reshape(1, -1).shape)   # (1, 3) — CORRECT

# Write in your notes: when does sklearn complain about shape?

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(2, 2, 3)
(2, 6)
(3,)
(1, 3)


### Vectorization vs Loops

In [6]:
import numpy as np
import time

# PROBLEM 1: Square each element in an array of 1 million numbers

data = np.random.randn(1_000_000)

# Loop version
start = time.time()
result_loop = []
for x in data:
    result_loop.append(x ** 2)
loop_time = time.time() - start
print(f"Loop: {loop_time:.4f} seconds")

# Vectorized version 
start = time.time()
result_vec = data ** 2
vec_time = time.time() - start
print(f"Vectorized: {vec_time:.4f} seconds")

print(f"Speedup: {loop_time / vec_time:.1f}x faster")

# Verify same result
print("Same result:", np.allclose(result_loop, result_vec))

Loop: 0.1679 seconds
Vectorized: 0.0021 seconds
Speedup: 78.2x faster
Same result: True


In [7]:
# PROBLEM 2: Normalize an array (subtract mean, divide by std)

data = np.random.randn(500_000) # just leave the cell running and let it finish 
                                # you will be shocked to see the results

# loops
result = [] 
start = time.time()
for x in data:
    result.append((x-np.mean(data))/np.std(data))
loop_time = time.time()-start
print(f"Loop: {loop_time:.4f} seconds")

# vectorized 
start = time.time()
result = (data-np.mean(data))/np.std(data)
vec_time = time.time()-start
print(f"Vectorized: {vec_time:.4f} seconds")


print(f"Speedup: {loop_time / vec_time:.1f}x faster")


KeyboardInterrupt: 

In [ ]:
# PROBLEM 3: Count how many elements are above the mean

data = np.random.randn(500_0000)

mean = np.mean(data)

# loops
start = time.time()
count = 0
for i in data:
    if i>mean:
        count += 1
print('Loops - total elements above mean :{}'.format(count))
loop_time = time.time()-start
print(f"Loop: {loop_time:.4f} seconds")

# vectorized
start = time.time()
count = data[data>mean].size
print('Vectorized - total elements above mean :{}'.format(count))
vec_time = time.time()-start
print(f"Vectorized: {vec_time:.4f} seconds")


print(f"Speedup: {loop_time / vec_time:.1f}x faster")



Loops - total elements above mean :2498281
Loop: 0.5486 seconds
Loops - total elements above mean :2498281
Vectorized: 0.0255 seconds
Speedup: 21.5x faster


In [ ]:
# PROBLEM 4: Compute dot product of two arrays manually

arr1 = np.random.randn(5_000_000)
arr2 = np.random.randn(5_000_000)

# loops
start = time.time()
result = 0
for i,j in zip(arr1,arr2):
    result += i*j
print('dot product using loops: {:.2f}'.format(result))

loop_time = time.time()-start
print(f"Loop: {loop_time:.4f} seconds")

# vectorized
start = time.time()
result = np.sum(arr1*arr2)
print('dot product using vectorized: {:.2f}'.format(result))

vec_time = time.time()-start
print(f"Vectorized: {vec_time:.4f} seconds")


print(f"Speedup: {loop_time / vec_time:.1f}x faster")

dot product using loops: 4029.89
Loop: 1.0446 seconds
dot product using vectorized: 4029.89
Vectorized: 0.0217 seconds
Speedup: 48.0x faster


In [ ]:
# PROBLEM 5: Find the row with the maximum sum in a 2D matrix

data_2d = np.random.randn(100000, 50)

# loops
start = time.time()

ind = 0
max_sum = 0
for i in range(len(data_2d)):
    rw_sm = sum(data_2d[i])
    if max_sum < rw_sm:
        max_sum = rw_sm
        ind = i

print('Loops - row number {} have max sum {:.2f}'.format(ind,max_sum))

loop_time = time.time()-start
print(f"Loop: {loop_time:.4f} seconds")

# vectorized
start = time.time()
sums = np.sum(data_2d,axis=1)
ind = np.argmax(sums)
max_sum = sums[ind]

print('Vectorized - row number {} have max sum {:.2f}'.format(ind,max_sum))

vec_time = time.time()-start
print(f"Vectorized: {vec_time:.4f} seconds")


print(f"Speedup: {loop_time / vec_time:.1f}x faster")


Loops - row number 73883 have max sum 32.81
Loop: 0.3310 seconds
Vectorized - row number 73883 have max sum 32.81
Vectorized: 0.0036 seconds
Speedup: 91.7x faster


### Broadcasting 

In [ ]:
# Broadcasting Rule: NumPy expands smaller arrays to match larger ones
# The rule: dimensions are compared RIGHT to LEFT
# Compatible if: they are equal, or one of them is 1

# Example 1: scalar + array (simplest case)
arr = np.array([1, 2, 3, 4])
result = arr + 10     # 10 is broadcast to [10, 10, 10, 10]
print(result)         # [11, 12, 13, 14]

# Example 2: column vector + row vector (most confusing case)
col = np.array([[1], [2], [3]])    # shape (3, 1)
row = np.array([10, 20, 30, 40])  # shape (4,) → treated as (1, 4)
result = col + row
print(result.shape)   # PREDICT: what shape?
print(result)         # PREDICT: what values?

# Example 3: Normalize each column of a matrix (real ML use case)
data = np.random.randn(100, 5)    # 100 samples, 5 features
mean = data.mean(axis=0)          # shape (5,) — mean of each column
std = data.std(axis=0)            # shape (5,) — std of each column
normalized = (data - mean) / std  # broadcasting makes this work
print(normalized.shape)           # (100, 5) — same shape
print(normalized.mean(axis=0))    # should be ~[0, 0, 0, 0, 0]
print(normalized.std(axis=0))     # should be ~[1, 1, 1, 1, 1]

# INTENTIONALLY break broadcasting
try:
    arr1 = np.ones((3, 4))
    arr2 = np.ones((3, 3))
    result = arr1 + arr2   # This will fail — why?
except ValueError as e:
    print(f"Error: {e}")

[11 12 13 14]
(3, 4)
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
(100, 5)
[-7.15399961e-17 -3.33066907e-17  7.77156117e-17 -4.82947016e-17
  1.37667655e-16]
[1. 1. 1. 1. 1.]
Error: operands could not be broadcast together with shapes (3,4) (3,3) 


### Aggregations and Axis 

In [ ]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# PREDICT each output before running:
print(np.sum(data))           # sum of everything
print(np.sum(data, axis=0))   # sum along columns (collapse rows)
print(np.sum(data, axis=1))   # sum along rows (collapse columns)

print(np.mean(data, axis=0))  # mean of each column
print(np.max(data, axis=1))   # max of each row
print(np.argmax(data, axis=1)) # INDEX of max in each row

# Stack and concatenate — used when combining datasets
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

vertical = np.vstack([a, b])      # stack rows — PREDICT shape
horizontal = np.hstack([a, b])    # stack columns — PREDICT shape
print(vertical.shape)
print(horizontal.shape)

print(vertical)
print(horizontal)

45
[12 15 18]
[ 6 15 24]
[4. 5. 6.]
[3 6 9]
[2 2 2]
(4, 2)
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


### Vectorization 10-problems

In [19]:
# PROBLEM 1: Euclidean distance between two points

p1 = np.random.randint(1,10000,1_000_000).astype(np.float64)
p2 = np.random.randint(1,10000,1_000_000).astype(np.float64)

# loops
start = time.time()
distance = sum([(x-y)**2 for x,y in zip(p1,p2)])**0.5   
loop_time = time.time()-start
print('distance between points using loops: {:.2f}'.format(distance))
print(f"Loop: {loop_time:.4f} seconds")

# vectorized 
start = time.time()
distance = np.linalg.norm(p1-p2)
vec_time = time.time()-start
print('distance between points using vectorization: {:.2f}'.format(distance))
print(f"Vectorized: {vec_time:.4f} seconds")


print(f"Speedup: {loop_time / vec_time:.1f}x faster")



distance between points using loops: 4081921.21
Loop: 0.2340 seconds
distance between points using vectorization: 4081921.21
Vectorized: 0.0045 seconds
Speedup: 51.6x faster


In [20]:
# PROBLEM 1: Euclidean distance between two points

p1 = np.random.randint(1,10000,1_000_000).astype(np.float64)
p2 = np.random.randint(1,10000,1_000_000).astype(np.float64)

# loops
start = time.time()
distance = sum([(x-y)**2 for x,y in zip(p1,p2)])**0.5   
loop_time = time.time()-start
print('distance between points using loops: {:.2f}'.format(distance))
print(f"Loop: {loop_time:.4f} seconds")

# vectorized 
start = time.time()
distance = np.linalg.norm(p1-p2)
vec_time = time.time()-start
print('distance between points using vectorization: {:.2f}'.format(distance))
print(f"Vectorized: {vec_time:.4f} seconds")


print(f"Speedup: {loop_time / vec_time:.1f}x faster")



distance between points using loops: 4082294.88
Loop: 0.2274 seconds
distance between points using vectorization: 4082294.88
Vectorized: 0.0028 seconds
Speedup: 80.6x faster


In [21]:
# PROBLEM 2: Min-max normalization of array
# Formula: (x - min) / (max - min)

array = np.random.randn(5_0000_000)

# loops
start = time.time()

mx = max(array)
mn = min(array)
results = []
for num in array:
    results.append((num-mn)/(mx-mn))

loop_time = time.time()-start
print('array normalized using loops.')
print(f"Loop: {loop_time:.4f} seconds")

# vectorized 
start = time.time()
results = (array - np.min(array))/(np.max(array) - np.min(array))
vec_time = time.time()-start
print('array normalized using vectorization.')
print(f"Vectorized: {vec_time:.4f} seconds")


print(f"Speedup: {loop_time / vec_time:.1f}x faster")

array normalized using loops.
Loop: 16.8746 seconds
array normalized using vectorization.
Vectorized: 0.9325 seconds
Speedup: 18.1x faster


In [22]:
# PROBLEM 3: Compute pairwise differences between two arrays

a = np.random.randn(5_000)      
b = np.random.randn(5_000)   

# loops
start = time.time()
differences = [i-j for i in a for j in b]
loop_time = time.time()-start
print(f"Loop: {loop_time:.4f} seconds")

# vectorized 
start = time.time()
differences = a.reshape(a.shape[0],1) - b # using reshaping and broadcasting
vec_time = time.time()-start
print(f"Vectorized: {vec_time:.4f} seconds")


print(f"Speedup: {loop_time / vec_time:.1f}x faster")

Loop: 2.4255 seconds
Vectorized: 0.2579 seconds
Speedup: 9.4x faster


In [23]:
data = np.random.randn(1_000_000)

# loop
data_loop = data.copy()
start = time.time()

for ind, val in enumerate(data_loop):
    if val < 0:
        data_loop[ind] = 0

loop_time = time.time() - start

# vectorized
data_vec = data.copy()
start = time.time()

data_vec[data_vec < 0] = 0

vec_time = time.time() - start

print(f"Loop: {loop_time:.4f} seconds")
print(f"Vectorized: {vec_time:.4f} seconds")
print(f"Speedup: {loop_time / vec_time:.1f}x faster")

Loop: 0.1732 seconds
Vectorized: 0.0059 seconds
Speedup: 29.4x faster


In [24]:
data = np.arange(1, 1_000_000)  # larger input

# loop
start = time.time()
cumsum_loop = [data[0]]
for num in data[1:]:
    cumsum_loop.append(cumsum_loop[-1] + num)
loop_time = time.time() - start

# vectorized
start = time.time()
cumsum_vec = np.cumsum(data)
vec_time = time.time() - start

# validation
assert np.allclose(cumsum_loop, cumsum_vec), "check logic answers not matching"

print(f"Loop: {loop_time:.4f} seconds")
print(f"Vectorized: {vec_time:.4f} seconds")
print(f"Speedup: {loop_time / vec_time:.1f}x faster")

Loop: 0.1378 seconds
Vectorized: 0.0039 seconds
Speedup: 35.1x faster


In [25]:
# PROBLEM 7: Compute correlation between two arrays manually

x = np.random.randn(10_000_000)
y = 2 * x + np.random.randn(10_000_000) * 0.5

# loop
start = time.time()

N = len(x)
x_mean = sum(x)/N 
y_mean = sum(y)/N
cov_loop = sum((x-x_mean)*(y-y_mean))/(N-1)
stdx_loop = (sum((x-x_mean)**2)/(N-1))**0.5
stdy_loop = (sum((y-y_mean)**2)/(N-1))**0.5
corrcoef_loop = cov_loop / (stdx_loop*stdy_loop)

loop_time = time.time() - start


# vectorized
start = time.time()
corrcoef_vect = np.corrcoef(x,y)
vect_time = time.time()-start


print('correcoef :- \nLoop - {}\nVectorization - {}'.format(corrcoef_loop,corrcoef_vect[0][1]))

print(f"Loop: {loop_time:.4f} seconds")
print(f"Vectorized: {vec_time:.4f} seconds")
print(f"Speedup: {loop_time / vec_time:.1f}x faster")




correcoef :- 
Loop - 0.9701244971201531
Vectorization - 0.9701244971200618
Loop: 2.7970 seconds
Vectorized: 0.0039 seconds
Speedup: 712.4x faster


In [37]:
# PROBLEM 8: One-hot encode a categorical array

labels = np.random.randint(0, 10, size=10_000_000)  # 10 classes

# loop
start = time.time()

num_classes = 10

onehot_loop = np.zeros((len(labels), num_classes), dtype=int)

for i in range(len(labels)):
    onehot_loop[i][labels[i]] = 1

loop_time = time.time() - start


# vectorized
start = time.time()

onehot_vect = np.eye(num_classes, dtype=int)[labels]

vect_time = time.time() - start


print('One-hot encoding completed.')

print(f"Loop: {loop_time:.4f} seconds")
print(f"Vectorized: {vect_time:.4f} seconds")
print(f"Speedup: {loop_time / vect_time:.1f}x faster")

One-hot encoding completed.
Loop: 3.1310 seconds
Vectorized: 0.8433 seconds
Speedup: 3.7x faster


In [27]:
# PROBLEM 9: Moving average with window size 3

data = np.random.randn(10_000_000)

# loop
start = time.time()

window = 3

movingavg_loop = []

for i in range(len(data) - window + 1):
    avg = sum(data[i:i+window]) / window
    movingavg_loop.append(avg)

movingavg_loop = np.array(movingavg_loop)

loop_time = time.time() - start


# vectorized
start = time.time()

movingavg_vect = np.convolve(
    data,
    np.ones(window) / window,
    mode='valid'
)

vect_time = time.time() - start


print(
    '\nMoving Average :- \n'
    'Loop - \n{}\n'
    'Vectorization - \n{}'.format(
        movingavg_loop[:10],
        movingavg_vect[:10]
    )
)

print(f"Loop: {loop_time:.6f} seconds")
print(f"Vectorized: {vect_time:.6f} seconds")
print(f"Speedup: {loop_time / vect_time:.1f}x faster")


Moving Average :- 
Loop - 
[-1.10530679 -0.49642449 -0.34078183 -0.06373784 -0.31338214  0.11325132
 -0.09640748 -0.39930133 -0.09035735  0.03810831]
Vectorization - 
[-1.10530679 -0.49642449 -0.34078183 -0.06373784 -0.31338214  0.11325132
 -0.09640748 -0.39930133 -0.09035735  0.03810831]
Loop: 13.184128 seconds
Vectorized: 0.025527 seconds
Speedup: 516.5x faster


In [28]:
# PROBLEM 10: Clip array values between -2 and 2
data = np.random.randn(1_000_000) * 5

# loop
start = time.time()

clipped_loop = np.empty_like(data)

for i in range(len(data)):

    if data[i] < -2:
        clipped_loop[i] = -2

    elif data[i] > 2:
        clipped_loop[i] = 2

    else:
        clipped_loop[i] = data[i]

loop_time = time.time() - start


# vectorized
start = time.time()

clipped_vect = np.clip(data, -2, 2)

vect_time = time.time() - start


print(
    '\nClipped Array :- \n'
    'Loop - \n{}\n'
    'Vectorization - \n{}'.format(
        clipped_loop[:10],
        clipped_vect[:10]
    )
)

print(f"Loop: {loop_time:.6f} seconds")
print(f"Vectorized: {vect_time:.6f} seconds")
print(f"Speedup: {loop_time / vect_time:.1f}x faster")


Clipped Array :- 
Loop - 
[-0.946974    2.          2.          2.         -2.         -2.
 -1.41238768 -1.08008213  2.          2.        ]
Vectorization - 
[-0.946974    2.          2.          2.         -2.         -2.
 -1.41238768 -1.08008213  2.          2.        ]
Loop: 0.474236 seconds
Vectorized: 0.002347 seconds
Speedup: 202.1x faster


### 10-problem vectorization benchmark

In [38]:
results = {
    'Problem': ['Euclidean', 'MinMax', 'Pairwise', 'ReLU', 'CumSum',
                'MatMul', 'Correlation', 'OneHot', 'MovingAvg', 'Clip'],

    'Loop Time (s)': [
        0.2274,     # Euclidean
        16.8746,    # MinMax
        0.2340,     # Pairwise
        0.1378,     # ReLU
        0.1732,     # CumSum
        2.4255,     # MatMul
        2.7970,     # Correlation
        3.1310,     # OneHot 
        13.1841,    # MovingAvg
        0.4742      # Clip
    ],

    'Vec Time (s)': [
        0.0028,     # Euclidean
        0.9325,     # MinMax
        0.0045,     # Pairwise
        0.0039,     # ReLU
        0.0059,     # CumSum
        0.2579,     # MatMul
        0.0039,     # Correlation
        0.8433,     # OneHot 
        0.0255,     # MovingAvg
        0.0023      # Clip
    ],

    'Speedup': [
        80.6,       # Euclidean
        18.1,       # MinMax
        51.6,       # Pairwise
        35.1,       # ReLU
        29.4,       # CumSum
        9.4,        # MatMul
        712.4,      # Correlation
        3.7,        # OneHot
        516.5,      # MovingAvg
        202.1       # Clip
    ]
}


# Display as a formatted table
for i, prob in enumerate(results['Problem']):

    print(
        f"{prob:15s} | "
        f"Loop: {results['Loop Time (s)'][i]:.4f}s | "
        f"Vec: {results['Vec Time (s)'][i]:.6f}s | "
        f"Speedup: {results['Speedup'][i]:.0f}x"
    )

Euclidean       | Loop: 0.2274s | Vec: 0.002800s | Speedup: 81x
MinMax          | Loop: 16.8746s | Vec: 0.932500s | Speedup: 18x
Pairwise        | Loop: 0.2340s | Vec: 0.004500s | Speedup: 52x
ReLU            | Loop: 0.1378s | Vec: 0.003900s | Speedup: 35x
CumSum          | Loop: 0.1732s | Vec: 0.005900s | Speedup: 29x
MatMul          | Loop: 2.4255s | Vec: 0.257900s | Speedup: 9x
Correlation     | Loop: 2.7970s | Vec: 0.003900s | Speedup: 712x
OneHot          | Loop: 3.1310s | Vec: 0.843300s | Speedup: 4x
MovingAvg       | Loop: 13.1841s | Vec: 0.025500s | Speedup: 516x
Clip            | Loop: 0.4742s | Vec: 0.002300s | Speedup: 202x


### Broadcasting Deep Dive + Edge Cases

In [3]:
# REAL ML USE CASE: Subtract mean from each row (not column)
data = np.random.randn(5, 3)   # 5 samples, 3 features
row_means = data.mean(axis=1)  # shape (5,) — mean of each row
print(row_means.shape)

# This will FAIL — why?
# result = data - row_means

# Fix: reshape row_means to (5, 1) so broadcasting works
result = data - row_means.reshape(-1, 1)   # or row_means[:, np.newaxis]
print(result.shape)   # (5, 3) — correct

# REAL ML USE CASE: Cosine similarity between two matrices
# (Used in recommendation systems and NLP)
a = np.random.randn(10, 50)   # 10 query vectors, 50 dimensions
b = np.random.randn(20, 50)   # 20 document vectors, 50 dimensions

# Normalize each row to unit length
a_norm = a / np.linalg.norm(a, axis=1, keepdims=True)
b_norm = b / np.linalg.norm(b, axis=1, keepdims=True)

# Compute all pairwise similarities
similarity = a_norm @ b_norm.T    # shape (10, 20)
print(similarity.shape)           # 10 queries × 20 documents
print("Max similarity:", similarity.max())
print("Min similarity:", similarity.min())

(5,)
[[ 0.08306034]
 [ 1.06710123]
 [ 0.14989004]
 [ 0.29683832]
 [-0.79435655]]
(10, 20)
Max similarity: 0.3504513845434737
Min similarity: -0.29187039464347764


### NumPy Random

In [4]:
# Always set a seed for reproducibility — this is professional practice
rng = np.random.default_rng(seed=42)   # modern way (numpy 1.17+)

# Different distributions
normal = rng.normal(loc=0, scale=1, size=(1000,))     # Gaussian
uniform = rng.uniform(low=0, high=1, size=(1000,))    # Uniform
integers = rng.integers(low=0, high=10, size=(100,))  # Random integers

# Shuffle — for dataset splitting
data = np.arange(100)
rng.shuffle(data)   # in-place shuffle
print(data[:10])    # first 10 after shuffle

# Choice — for sampling
sample = rng.choice(data, size=20, replace=False)   # without replacement
print(sample)

# WHY THIS MATTERS: if you don't set a seed, your results change every run.
# In ML, this breaks reproducibility. Always set seeds.

[54 61 69 34 88 63 67 94 46 25]
[82 11 88  2 85 86 35 42 46 13 72 23 37 29 69 41 22 89 30 87]


### Final Summary

## Week 1 Summary — What I Can Now Do

**Vectorization:** I can rewrite any Python loop as a NumPy vectorized operation and measure the speedup.

**Broadcasting:** I understand that NumPy aligns dimensions from the right, and dimensions must be equal or 1.

**Reshaping:** I know that `reshape(-1, 1)` turns a 1D array into a column vector, which is the most common fix for sklearn shape errors.

**Debugging:** I can use `pdb` to step through code and inspect variables at any point.

**Professional Python:** I write functions with type hints, docstrings, and proper error handling.

---

## Benchmark Results

| Problem | Loop Time | Vectorized Time | Speedup |
|----------|------------|-----------------|----------|
| Euclidean Distance | 0.2274s | 0.002800s | 81x |
| MinMax Scaling | 16.8746s | 0.932500s | 18x |
| Pairwise Distance | 0.2340s | 0.004500s | 52x |
| ReLU Activation | 0.1378s | 0.003900s | 35x |
| Cumulative Sum | 0.1732s | 0.005900s | 29x |
| Matrix Multiplication | 2.4255s | 0.257900s | 9x |
| Correlation Matrix | 2.7970s | 0.003900s | 712x |
| One-Hot Encoding | 3.1310s | 0.843300s | 4x |
| Moving Average | 13.1841s | 0.025500s | 516x |
| Clipping Values | 0.4742s | 0.002300s | 202x |

---

## Things That Surprised Me

1. Some NumPy operations were hundreds of times faster than Python loops — especially correlation matrices and moving averages.

2. Broadcasting felt confusing initially, but once I understood “align dimensions from the right,” most shape issues became predictable.

3. The biggest performance gains came not from micro-optimizations, but from changing the computation model entirely — replacing Python iteration with vectorized array operations.

4. Even basic preprocessing operations like clipping and ReLU become dramatically faster when implemented with NumPy vectorization.

5. Matrix multiplication showed a smaller relative speedup because NumPy already uses highly optimized low-level linear algebra libraries such as BLAS and LAPACK.